---
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
    networks:
      - techlog-net
    logging:
      options:
        max-size: "20m"  
        max-file: "1"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gillilab-techlog-be:latest
    container_name: gillilab-techlog-be
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload
    ports:
      - 3001:3000
    volumes:
      - ./backend:/backend
    networks:
      - techlog-net
    logging:
      options:
        max-size: "20m"  
        max-file: "1"

networks:
  techlog-net:
    driver: bridge
